Fix API change for rain forecast
hacf-fr/meteo-france-weather-card pull request #1
Opened 2020-10-13 00:29 UTC by ioull

2020-10-14 18:23 UTC, oncleben31 approved these changes
LGTM but I'm not a JS expert.

2020-10-15 08:22 UTC, Quentame requested changes

2020-10-15 08:22 UTC, Quentame commented on dist/meteo-france-weather-card.js
> +                            <span class="pluie-element" style="opacity: ${forecast[1]}" title="${forecast[2] + " " + ((forecast[0] == 0) ? "actuellement" : "dans " + forecast[0] + " min")}">
```suggestion
                            <span class="pluie-element" style="opacity: ${forecast[1]}" title="${forecast[2] + " " + (forecast[0] == 0 ? "actuellement" : "dans " + forecast[0] + " min")}">
```

---

OR for better readability:
```suggestion
                            <span class="pluie-element"
                                  style="opacity: ${forecast[1]}"
                                  title="${forecast[2] + " " + (forecast[0] == 0 ? "actuellement" : "dans " + forecast[0] + " min")}">
```

2020-10-15 08:22 UTC, Quentame commented on dist/meteo-france-weather-card.js
> +	    ['Pluie forte',    "1"]
```suggestion
	    ['Temps sec', 0.1],
	    ['Pluie faible', 0.4],
	    ['Pluie modérée', 0.7],
	    ['Pluie forte', 1]
```
This should work, otherwise keep the string

2020-10-15 08:22 UTC, Quentame commented on dist/meteo-france-weather-card.js
>          .pluie-element.unknown {
should be removed

2020-10-15 08:22 UTC, Quentame commented on dist/meteo-france-weather-card.js
> +      time = time.substring(0, time.length-4);
4 represents " min" ?

you can simply do something like:
```suggestion
      time = time.replace('min', '').trim();
```

2020-10-15 11:46 UTC, ioull commented on dist/meteo-france-weather-card.js
>          .pluie-element.unknown {
I don't understand

2020-10-15 12:08 UTC, Quentame commented on dist/meteo-france-weather-card.js
>          .pluie-element.unknown {
`<span title='Données indisponibles' class='pluie-element unknown'></span>` does not exist in the DOM anymore.

See L345 https://github.com/hacf-fr/meteo-france-weather-card/pull/1/files#diff-2338c77953350789b5ca85a4bed92236be01cc9320637724d36dafbb1cf3e723L345

Or maybe it exists at an other place I did not see.

2020-10-15 12:17 UTC, ioull reviewed
Fixed !

2020-10-15 12:17 UTC, ioull commented on dist/meteo-france-weather-card.js
>          .pluie-element.unknown {
OK ! I did'nt understand that you were talking about  .pluie-element.unknown element ;-) 
It is removed now !

2020-10-15 12:37 UTC, Quentame approved these changes

2020-10-15 12:39 UTC, merged